= Centos 7 developer workstation on VirtualBox notes


#### Update base install and Add development libraries 
This is to allow virtualbox guest utils to install:

- yum update
- yum groupinstall "Development tools"
- yum install kernel-devel
- yum install kernel-devel-3.10.0-229.el7.x86_64  (following error message from VBosLinuxAdditions.run)
- reboot

&nbsp;

#### Install virtualbox additions

- mount the VBOXADDITIONS cd through the virtual box devices menu
- cd /mnt; mkdir cdrom; mount /dev/cdrom /mnt/cdrom
- cd /mnt/cdrom
- ./VBoxLinuxAdditions.run

&nbsp;

#### Setup eclipse
- download from eclipse.org
- gunzip and tar xf the file, creates "eclipse" folder holding installation.
- move eclipse to /usr/local
- create a gnome desktop menu entry by editing /usr/share/applications/eclipse.desktop
    add the following text...

&nbsp;

     
#### Bring sanity to gnome
- Hack the gnome css, because gnome ships with some bad defaults but allows very little customization via the gui.
Create ~/.config/gtk-3.0/gtk.css to override the defaults...

  .header-bar.default-decoration {
    padding-top: 3px;
    padding-bottom: 3px;
  }
  .header-bar.default-decoration .button.titlebutton {
    padding-top: 2px;
    padding-bottom: 2px;
  }

#### The SELinux problem
   Sympton: get a 403 error from web pages on localhost.
   Apache log in /var/logs/httpd says "Permission denied:... file permissions deny server access: /var/www/index.html" 
   The file permissions all the way down to index.html are completely open.

The problem: SELinux is enabled by default.  Dont want this on a single user locally hosted development VM.
Fix: 
   $ sudo setenforce 0
     now switch off selinux bye editing /etc/sysconfig/selinux.  alter the line "SELINUX=enforcing" to "SELINUX=disabled"
     
     
